# Generated by Django 3.1.1 on 2020-09-01 12:05

from django.db import migrations, models
import payments.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditcardnumber', models.CharField(max_length=16, validators=[payments.validators.creditcard_validator])),
                ('cardholder', models.CharField(max_length=50)),
                ('expirationdate', models.DateField(validators=[payments.validators.date_validator])),
                ('securitycode', models.CharField(max_length=3, validators=[payments.validators.security_validator])),
                ('amount', models.IntegerField(validators=[payments.validators.amount_validator])),
            ],
        ),
    ]
