# Generated by Django 3.1.1 on 2020-09-02 09:36

from django.db import migrations, models
import payments.validators


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='securitycode',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[payments.validators.security_validator]),
        ),
    ]
