# Generated by Django 3.1.1 on 2020-09-03 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_executiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='executiontime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 23, 45, 343849, tzinfo=utc)),
        ),
    ]
