# Generated by Django 3.1.1 on 2020-09-06 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20200906_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='executiontime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 12, 42, 48, 264007, tzinfo=utc)),
        ),
    ]
